package com.github.secretx33.imagetopdf.convert

const val ORIENTATION_HORIZONTAL = 1
const val ORIENTATION_MIRROR_HORIZONTAL = 2
const val ORIENTATION_ROTATE_180 = 3
const val ORIENTATION_MIRROR_VERTICAL = 4
const val ORIENTATION_MIRROR_HORIZONTAL_AND_ROTATE_270 = 5
const val ORIENTATION_ROTATE_90 = 6
const val ORIENTATION_MIRROR_HORIZONTAL_AND_ROTATE_90 = 7
const val ORIENTATION_ROTATE_270 = 8