name: Native Build

on:
  workflow_dispatch:
  workflow_call:

jobs:
  native_build:
    name: Native Build
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup GraalVM 25
        uses: graalvm/setup-graalvm@f744c72a42b1995d7b0cbc314bde4bace7ac1fe1 # v1.5.0
        with:
          java-version: 25
          distribution: graalvm
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@0723195856401067f7a2779048b490ace7a47d7c # v5.0.2

      - name: Execute Gradle build
        run: ./gradlew nativeCompile --no-daemon

      - name: Upload artifact
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: binaries
          path: build/libs/*
          if-no-files-found: error