name: Native Build

on:
  workflow_dispatch:
  workflow_call:

jobs:
  native_build:
    name: Native Build
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup GraalVM 17
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: 17
          distribution: graalvm
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@ac638b010cf58a27ee6c972d7336334ccaf61c96 # v4.4.1

      - name: Execute Gradle build
        run: ./gradlew nativeCompile --no-daemon

      - name: Upload artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: binaries
          path: build/libs/*
          if-no-files-found: error