name: Native Build

on:
  workflow_dispatch:
  workflow_call:

jobs:
  native_build:
    name: Native Build
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup GraalVM 17
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: 17
          distribution: graalvm
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: ./gradlew nativeCompile --no-daemon

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: build/libs/*
          if-no-files-found: error